services:
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  back:
    build: ../back
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres_db:5432/${POSTGRES_DATABASE}
      - spring.datasource.username=${POSTGRES_USER}
      - spring.datasource.password=${POSTGRES_PASSWORD}
    ports:
      - 9000:9000
    depends_on:
      - postgres_db

volumes:
  postgres_data:
    driver: local