services:
  postgres_db:
    profiles: ["dev", "prod"]
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  back:
    profiles: ["dev", "prod"]
    build: ../back
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres_db:5432/${POSTGRES_DATABASE}
      - spring.datasource.username=${POSTGRES_USER}
      - spring.datasource.password=${POSTGRES_PASSWORD}
    ports:
      - 9000:9000
    depends_on:
      - postgres_db
    networks:
      - app-network
 
  
  front:
    profiles:
      - prod
    build: ../front
    ports:
      - 80:80
    depends_on:
      - back
    networks:
      - app-network   

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge